name: Build hadoop


env:
  PRODUCT_NAME: hadoop
  KUBEDOOP_VERSION: ${{ github.ref_type == 'tag' && github.ref_name || '0.0.0-dev' }}
  REGISTRY: quay.io/huagang

on:
  push:
    branches:
      - main
    tags:
        - '\d+.\d+.\d+*'
    paths:
      - hadoop/**
      - kubedoop-base/**
      - vector/**
      - java-base/**
      - java-devel/**
      - .github/actions/**
      - .github/workflows/build_hadoop.yaml
  pull_request:
    branches:
      - main
    paths:
      - hadoop/**
      - kubedoop-base/**
      - vector/**
      - java-base/**
      - java-devel/**
      - .github/actions/**
      - .github/workflows/build_hadoop.yaml



jobs:
  product-shard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get product versions
        id: product-shard
        uses: ./.github/actions/product-shard
        with:
          product_name: ${{ env.PRODUCT_NAME }}
    outputs:
      versions: ${{ steps.product-shard.outputs.versions }}

  build-image:
    name: Build ${{ matrix.version }} on ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    # if: ${{ github.repository_owner == 'zncdatadev' && github.event_name == 'push' }}
    needs:
      - product-shard
    strategy:
      matrix:
        version: ${{fromJson(needs.product-shard.outputs.versions)}}
        arch: [amd64, arm64]
        include:
          - arch: amd64
            platform: linux/amd64
            runner: ubuntu-latest
          - arch: arm64
            platform: linux/arm64
            runner: ubicloud-standard-8-arm-ubuntu-2404
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Display OS Information
        run: |
          echo "Running on $(uname -a)"
          echo "Architecture: $(arch)"
          echo "CPU Information:"
          lscpu
          echo "Memory Information:"
          free -h
          echo "Disk Usage:"
          df -h

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Run build
        uses: ./.github/actions/build-and-push
        with:
          registry: ${{ env.REGISTRY }}
          registry_username: ${{ secrets.QUAY_USERNAME }}
          registry_password: ${{ secrets.QUAY_PASSWORD }}
          kubedoop_version: ${{ env.KUBEDOOP_VERSION }}
          product_name: ${{ env.PRODUCT_NAME }}
          product_version: ${{ matrix.version }}
          platform: ${{ matrix.platform }}
          arch_suffix: true
          push: ${{ github.event_name == 'push' }}
          sign: ${{ github.ref_type == 'tag' }}
          action_debug: 'false' # enable debug for the build-and-push action if needed


  build-manifest:
    name: Create multi-platform manifest for ${{ matrix.version }}
    runs-on: ubuntu-latest
    # if: ${{ github.repository_owner == 'zncdatadev' && github.event_name == 'push' }}
    needs:
      - product-shard
      - build-image
    strategy:
      matrix:
        version: ${{fromJson(needs.product-shard.outputs.versions)}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Publish multi-platform manifest
        uses: ./.github/actions/publish-manifest
        with:
          registry: ${{ env.REGISTRY }}
          registry_username: ${{ secrets.QUAY_USERNAME }}
          registry_password: ${{ secrets.QUAY_PASSWORD }}
          product_name: ${{ env.PRODUCT_NAME }}
          product_version: ${{ matrix.version }}
          kubedoop_version: ${{ env.KUBEDOOP_VERSION }}
          platforms: 'amd64,arm64'
          sign: ${{ github.ref_type == 'tag' }}
          action_debug: 'false'
